import os
import sys

VERTICES_FILE = "out_sam/mesh.vertices"
TRI_FILE = "SAM3DBody-cpp/onnx/body_mesh.tri"
OUTPUT_OBJ = "out_sam/test-2_mesh.obj"

def load_vertices(path):
    verts = []
    with open(path, "r") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            parts = line.split()
            if len(parts) == 3:
                verts.append(parts)
    return verts

def load_faces(path):
    faces = []
    with open(path, "rb") as f:
        raw = f.read()

    # Try text first
    try:
        text = raw.decode("utf-8")
        for line in text.splitlines():
            line = line.strip()
            if not line:
                continue
            parts = line.split()
            if len(parts) == 3:
                faces.append(parts)
        if faces:
            print(f"[OK] Parsed .tri as TEXT ({len(faces)} faces)")
            return faces
    except UnicodeDecodeError:
        pass

    # Fallback: binary int32 triplets
    import struct
    count = len(raw) // 12  # 3 int32 per triangle
    for i in range(count):
        a, b, c = struct.unpack_from("<iii", raw, i * 12)
        faces.append([str(a), str(b), str(c)])
    print(f"[OK] Parsed .tri as BINARY ({len(faces)} faces)")
    return faces

def main():
    if not os.path.isfile(VERTICES_FILE):
        print(f"[ERROR] Vertices file not found: {VERTICES_FILE}")
        print("        The C++ patch may not have run. Check workflow logs for [PATCH].")
        sys.exit(1)

    if not os.path.isfile(TRI_FILE):
        print(f"[ERROR] Triangle file not found: {TRI_FILE}")
        sys.exit(1)

    vertices = load_vertices(VERTICES_FILE)
    faces = load_faces(TRI_FILE)

    print(f"[*] Vertices: {len(vertices)}")
    print(f"[*] Faces:    {len(faces)}")

    # Detect face indexing (0-based vs 1-based) by checking min index
    min_idx = min(int(v) for f in faces for v in f)
    if min_idx == 0:
        print("[*] Faces appear 0-indexed. Converting to 1-indexed for OBJ.")
        faces = [[str(int(v) + 1) for v in f] for f in faces]
    else:
        print("[*] Faces appear 1-indexed. Keeping as-is.")

    os.makedirs(os.path.dirname(OUTPUT_OBJ), exist_ok=True)

    with open(OUTPUT_OBJ, "w") as f:
        f.write("# Generated by make_obj.py\n")
        for v in vertices:
            f.write(f"v {v[0]} {v[1]} {v[2]}\n")
        for face in faces:
            f.write(f"f {face[0]} {face[1]} {face[2]}\n")

    print(f"[OK] Wrote {OUTPUT_OBJ}")

if __name__ == "__main__":
    main()
