import os
import cv2
import json
import sys
import numpy as np
from datetime import datetime
from controlnet_aux import DWPoseDetector

def log(msg):
    print(msg, flush=True)

os.makedirs("inputs", exist_ok=True)
os.makedirs("artifacts", exist_ok=True)

log("="*60)
log("3D DETECTOR RUNNING (DWPose - Occlusion Specialist)")
log("="*60)

images = [f for f in os.listdir("inputs") if f.lower().endswith(('.png','.jpg','.jpeg'))]

if not images:
    log("No images found in inputs/ folder.")
    sys.exit(0)

log("Loading DWPose (Downloading weights on first run)...")
# DWPose automatically downloads the best weights from HuggingFace
detector = DWPoseDetector.from_pretrained("lllyasviel/ControlNet-v1-1")

# DWPose uses the standard 18-point COCO format
keypoint_names = [
    "nose", "left_eye", "right_eye", "left_ear", "right_ear",
    "left_shoulder", "right_shoulder", "left_elbow", "right_elbow",
    "left_wrist", "right_wrist", "left_hip", "right_hip",
    "left_knee", "right_knee", "left_ankle", "right_ankle"
]

model_name = "dwpose"

for img_name in images:
    img_path = os.path.join("inputs", img_name)
    log(f"\nProcessing: {img_name}")
    
    # Load image
    img = cv2.imread(img_path)
    if img is None:
        log(f"Could not read image: {img_name}")
        continue
        
    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    
    # Run DWPose
    log("Detecting pose (handling occlusions)...")
    detected_map = detector(img_rgb, output_type="np")
    
    # Extract keypoints from the detected map
    # DWPose returns a dictionary with 'candidate' (keypoints) and 'subset' (connections)
    candidates = detected_map['candidate']
    subsets = detected_map['subset']
    
    calculations = {}
    
    log("RAW CALCULATIONS (X=Left/Right, Y=Top/Bottom, Conf=Confidence):")
    log("-"*65)
    
    # Map the 18 COCO keypoints
    for i, name in enumerate(keypoint_names):
        # Find the keypoint in the candidates list based on the subset
        # DWPose subset format: [score, x, y, ...] for each person
        x, y, conf = 0.0, 0.0, 0.0
        
        if len(subsets) > 0:
            # Get the first detected person
            person_subset = subsets[0]
            if i < len(person_subset) and person_subset[i] >= 0:
                idx = int(person_subset[i])
                x = float(candidates[idx][0])
                y = float(candidates[idx][1])
                conf = float(candidates[idx][2])
        
        calculations[name] = {
            "X": round(x, 4),
            "Y": round(y, 4),
            "Confidence": round(conf, 4)
        }
        
        status = ""
        if conf < 0.30: # DWPose uses a slightly different confidence scale
            status = " [️ HIDDEN/GUESSED]"
            
        log(f"{name:<15} | X:{x:<7.4f} | Y:{y:<7.4f} | Conf:{conf}{status}")
    
    log("-"*65)
    
    base = os.path.splitext(img_name)[0]
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    
    img_out = f"artifacts/{base}_result_{model_name}_{ts}.jpg"
    json_out = f"artifacts/{base}_data_{model_name}_{ts}.json"
    
    # Save the visual skeleton map generated by DWPose
    # The detected_map is already an image with the skeleton drawn!
    skeleton_img = (detected_map * 255).astype(np.uint8)
    cv2.imwrite(img_out, cv2.cvtColor(skeleton_img, cv2.COLOR_RGB2BGR))
    
    with open(json_out, "w") as f:
        json.dump(calculations, f, indent=4)
    
    log(f"Saved to artifacts/ as {base}_*_{model_name}_*")

log("\nDONE! Check artifacts.")
